# Generated by Django 3.0.4 on 2020-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200319_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen1',
            field=models.ImageField(default='default.jpg', upload_to='comentario_pics'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='imagen2',
            field=models.ImageField(default='default.jpg', upload_to='comentario_pics'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='imagen3',
            field=models.ImageField(default='default.jpg', upload_to='comentario_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen1',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen2',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen3',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
