# Generated by Django 3.0.4 on 2020-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200319_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='info',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombres',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
