# Generated by Django 3.0.4 on 2020-03-22 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200322_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
