# Generated by Django 3.0.4 on 2020-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200322_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(default='default.jpg', upload_to='perfil_pics'),
        ),
    ]
