# Generated by Django 3.0.4 on 2020-03-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_perfil_imagen_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='info',
        ),
    ]
