# Generated by Django 3.0.4 on 2020-03-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_perfil_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
